hostname: localhost
domain: domain.com
guacadmin_password: password
mysql_password: password
radius_secret: sharedsecret
radius_host: 172.16.159.220
ldap_server: 172.16.159.220
ldap_user: guac_user
ldap_password: password
manual_connections:
  - conn_name: 'TEST-CONNECTION.domain.com - 172.16.159.220'
    hostname: '172.16.159.220'
    console-audio: 'true'
    console-audio': 'true'
    create-drive-path: 'true'
    drive-name: 'shared'
    drive-path: '/shared'
    enable-drive: 'true'
    enable-printing: 'true'
    ignore-cert: 'true'
    port: '3389'
    printer-name: 'RemotePrinter'
    security: 'tls'
    username: '${GUAC_USERNAME}'
    password: '${GUAC_PASSWORD}'
  - conn_name: 'TEST-CONNECTION2.domain.com - 172.16.159.220'
    hostname: '172.16.159.220'
    console-audio: 'true'
    console-audio': 'true'
    create-drive-path: 'true'
    drive-name: 'shared'
    drive-path: '/shared'
    enable-drive: 'true'
    enable-printing: 'true'
    ignore-cert: 'true'
    port: '3389'
    printer-name: 'RemotePrinter'
    security: 'tls'
    username: '${GUAC_USERNAME}'
    password: '${GUAC_PASSWORD}'